### ISSUE TITLE
@Validated 어노테이션 vs Validator

### ISSUE THREAD

**Issue by uoahy** [uoahy/baemin#1]
안녕하세요
저는 이번에 @Valid 어노테이션을 사용해 Request로 넘어오는 값들의 유효성 검사를 해줬는데요
Controller단에서 List<>로 넘어오는 값들에 대해서는 알아서 자동으로 리스트 내부에 들어가있는 값들을 검사하지 않더라구요
그래서 방법을 찾아보다가 Controller class 레벨에 @Validated 어노테이션을 추가하면 된다고해서 그렇게했는데
그러면 유효성 검사를 두 번 하는거라고 하더라구요
근데 제 생각엔 유효성 검사가 시간이 오래 걸리는 작업이 아니라서
따로 Validator로 구현해주는것보다는 유효성 검사를 두 번 실행하더라도 @Validated 어노테이션을 달아주는게 더 나을거같아 이렇게했는데 괜찮을까요?

**Comment by 9sanha** [comment]
지금은 단순한 유효성검사고 서비스의 크기와 사용하는 유저의 수가 많지 않기때문에 유효성검사를 두 번 하게 되어도 큰 상관은 없습니다!

하지만 추후에 10000명의 user가 유효성검사가 진행되는 api를 호출했을 때 성능의 차이가 보이기 시작할 것 같습니다. 서버는 티끌모아 태산을 만들 수 있기 때문에 가급적이면 불필요한 db접근이나 중복되는 유효성검사, 연산 등은 피해주시는게 좋습니다!

**Comment by uoahy** [comment]
넵 감사합니다
